CREATE TABLE TB_USER
(
    ID         BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(50)  NOT NULL,
    EMAIL      VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD   VARCHAR(500)  NOT NULL,
    CREATED_IN TIMESTAMP    NOT NULL,
    UPDATED_IN TIMESTAMP
);

CREATE TABLE TB_ROLE
(
    ID        BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE TB_USER_ROLE
(
    USER_ID    BIGINT(20),
    ROLE_ID    BIGINT(20),
    PRIMARY KEY (USER_ID, ROLE_ID),
    FOREIGN KEY (USER_ID) REFERENCES TB_USER (ID),
    FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLE (ID)
);



