INSERT INTO TB_USER (NAME, EMAIL, PASSWORD, CREATED_IN, UPDATED_IN)
VALUES ('Rodrigo Pereira', 'rodrigopereira.dev@gmail.com',
        '$2a$10$oqgalCIvrA8mMb5iU.VNDOeeQNSRPzHI7zUKgxjLSZhRwWNCAJzbC', CURRENT_TIMESTAMP, NULL);

INSERT INTO TB_ROLE (ROLE_NAME) VALUES ('ROLE_ADMIN');
INSERT INTO TB_ROLE (ROLE_NAME) VALUES ('ROLE_CLIENT');

INSERT INTO TB_USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
